import { ReactNode } from "react";
import styles from "./HowItWorks.module.css";

const kw  = (t: string) => <span className={styles.kw}>{t}</span>;
const fn  = (t: string) => <span className={styles.fn}>{t}</span>;
const ty  = (t: string) => <span className={styles.ty}>{t}</span>;
const str = (t: string) => <span className={styles.str}>{t}</span>;
const cmd = (t: string) => <span className={styles.cmd}>{t}</span>;
const cm  = (t: string) => <span className={styles.cm}>{t}</span>;
const va  = (t: string) => <span className={styles.va}>{t}</span>;

const STEPS: { num: string; verb: string; title: string; desc: string; code: ReactNode }[] = [
    {
        num: "01",
        verb: "WRITE",
        title: "Author in Amber",
        desc: "Use a clean, expressive syntax with types, closures, and real error handling. No Bash knowledge required.",
        code: (<>
            {kw("fun")} {fn("greet")}({va("name")}: {ty("Text")}) {"{"}{"\n"}
            {"    "}{fn("echo")} {str('"Hello, {')} {va("name")} {str('}!"')}{"\n"}
            {"}"}
        </>),
    },
    {
        num: "02",
        verb: "COMPILE",
        title: "Compile to Bash",
        desc: "Run amber compile and get a portable .sh file. Inspect every line — the output is always readable.",
        code: (<>
            {cmd("amber")} {kw("compile")} script.ab{"\n"}
            {cm("# outputs: script.sh")}
        </>),
    },
    {
        num: "03",
        verb: "DEPLOY",
        title: "Run Anywhere",
        desc: "Your output is plain Bash. No runtime, no install, no dependencies. Runs on any POSIX system.",
        code: (<>
            {cm("#!/bin/bash")}{"\n"}
            {cm("# Auto-generated by Amber")}{"\n"}
            {fn("greet")} {str('"world"')}
        </>),
    },
];

export default function HowItWorks() {
    return (
        <section className={styles.section} id="how-it-works">
            <div className={styles.eyebrow}>How It Works</div>
            <h2 className={styles.title}>Write once,<br />run anywhere.</h2>
            <p className={styles.subtitle}>
                Amber is a compile-step, not a runtime. Your scripts end up as portable Bash — readable, auditable, and universally compatible.
            </p>
            <div className={styles.steps}>
                {STEPS.map((step) => (
                    <div key={step.num} className={styles.step}>
                        <div className={styles.stepTop}>
                            <span className={styles.stepNum}>{step.num}</span>
                            <span className={styles.stepVerb}>{step.verb}</span>
                        </div>
                        <h3 className={styles.stepTitle}>{step.title}</h3>
                        <p className={styles.stepDesc}>{step.desc}</p>
                        <pre className={styles.stepCode}>{step.code}</pre>
                    </div>
                ))}
            </div>
        </section>
    );
}
